name: ESP-IDF Firmware Build

on:
  push:
    paths:
      - 'firmware/**'
  workflow_call:
  workflow_dispatch:

jobs:
  build-firmware:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5
          target: esp32c6
          path: 'firmware'
      - run: |
          mkdir -p release/bootloader
          cp firmware/build/flash_args release
          cp firmware/build/damppi.* release
          cp firmware/build/bootloader/bootloader.* release/bootloader
          cp -r firmware/build/partition_table release
      - uses: actions/upload-artifact@v4
        with:
          name: firmware-damppi
          path: release
